version: 2

jobs:
  build:
    docker:
      - image: archlinux

    steps:
      - checkout
      - run:
          name: Install required tools
          command: pacman -Sy --noconfirm base base-devel cmake clang git curl nlohmann-json doxygen gtest
      - run:
          name: Configure
          command: |
            rm -rf build
            mkdir build
            cd build
            cmake -DCMAKE_BUILD_TYPE=Debug -DIEX_BUILD_WARNINGS:BOOL=ON -DIEX_BUILD_TESTS:BOOL=ON -DIEX_BUILD_DOCUMENTATION:BOOL=ON -DIEX_TIDY:BOOL=ON ..
      - run:
          name: Style
          command: bash ././scripts/format.sh check
      - run:
          name: Compile
          command: cmake --build build/
      - run:
          name: Unit Test
          command: ././build/tests/unit_test
