version: 2

jobs:
  build:
    docker:
      - image: archlinux

    steps:
      - checkout
      - run:
          name: Install required tools
          command: pacman -Sy --noconfirm base base-devel cmake clang git curl nlohmann-json doxygen
      - run:
          name: Configure
          command: |
            rm -rf build
            mkdir build
            cd build
            cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_EXPORT_COMPILE_COMMANDS:BOOL=ON -DIEX_BUILD_DOCUMENTATION:BOOL=ON -DIEX_ENABLE_ALLWARNINGS:BOOL=ON -DIEX_BUILD_TESTING:BOOL=ON ..
      - run:
          name: Style
          command: ./style.sh
      - run:
          name: Compile
          command: cmake --build build/
      - run:
          name: Unit Test
          command: ././build/iex/test/unit_test
